title = "Tim in 't Veld"
baseURL = "http://tjveld.com/"
theme = "LoveIt"
languageCode = "en"
languageName = "English"
copyright = ""                  # copyright description used only for seo schema
enableRobotsTXT = true          # whether to use robots.txt
enableGitInfo = true            # whether to use git commit log
enableEmoji = true              # whether to use emoji code

# Menu config
[menu]
    [[menu.main]]
        weight = 1
        identifier = "posts"
        pre = ""
        post = ""
        name = "Posts"
        url = "/posts/"
        title = ""
    [[menu.main]]
        weight = 2
        identifier = "tags"
        pre = ""
        post = ""
        name = "Tags"
        url = "/tags/"
        title = ""
    [[menu.main]]
        weight = 3
        identifier = "categories"
        pre = ""
        post = ""
        name = "Categories"
        url = "/categories/"
        title = ""

[markup]
    [markup.highlight]      # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
        noClasses = false   # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)

[params]
    title = "Tim in 't Veld"    # website title for Open Graph and Twitter Cards
    description = "Personal Blog by Tim in 't Veld"     # website description for RSS, SEO, Open Graph and Twitter Cards

    defaultTheme = "auto"       # site default theme ["auto", "light", "dark"]
    gitRepo = "https://github.com/tjveld/tjveld.com"                # public git repo url only then enableGitInfo is true
    fingerprint = "sha512"      # LoveIt NEW | 0.1.1 which hash function used for SRI, when empty, no SRI is used
    dateFormat = "2 Jan 2006"   # LoveIt NEW | 0.2.0 date format
    images = ["/static/web-app-manifest-192x192.png"]   # website images for Open Graph and Twitter Cards

    [params.author]
    name = "Tim in 't Veld"

    [params.header]
        desktopMode = "fixed"   # desktop header mode ["fixed", "normal", "auto"]
        mobileMode = "auto"     # mobile header mode ["fixed", "normal", "auto"]
        
        [params.header.title]   # LoveIt NEW | 0.2.0 Header title config
            logo = ""
            name = "TJVELD"
            pre = ""
            post = ""
            typeit = false

    [params.home]   # Home page config 
        rss = 10    # LoveIt NEW | 0.2.0 amount of RSS pages

        [params.home.profile]
            enable = true                       # Gravatar Email for preferred avatar in home page
            title = "Tim in 't Veld"            # subtitle shown in home page (HTML format is supported)
            subtitle = "Computer says hi!"      # whether to use typeit animation for subtitle
            disclaimer = ""

            gravatarEmail = ""                  # URL of avatar shown in home page
            avatarURL = "/images/avatar.png"    # LoveIt CHANGED | 0.2.7 title shown in home page (HTML format is supported)

            typeit = true                       # whether to show social links
            social = true                       # LoveIt NEW | 0.2.0 disclaimer (HTML format is supported)
         
        [params.home.posts]
            enable = false                      # special amount of posts in each home posts page
            defaultHiddenFromHomePage = false   # default behavior when you don't set "hiddenFromHomePage" in front matter
            paginate = 6
            
    [params.footer]
        enable = true
        custom = ''         # LoveIt NEW | 0.2.0 Custom content (HTML format is supported)
        hugo = false        # LoveIt NEW | 0.2.0 whether to show Hugo and theme info
        copyright = true    # LoveIt NEW | 0.2.0 whether to show copyright info
        author = true       # LoveIt NEW | 0.2.0 whether to show the author
        since = 2026         # Site creation time
        # license info (HTML format is supported)
        license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

    [params.social]
        Instagram = "tjveld"
        GitHub = "tjveld"
        Linkedin = "tjveld"

    [params.page.code]
        copy = true
        maxShownLines = 50

    [params.page.share]
      enable = false

    [params.search]
        enable = true
        type = "lunr"           # type of search engine ["lunr", "algolia"]
        contentLength = 4000    # max index length of the chunked content
        placeholder = ""        # placeholder of the search bar
        maxResultLength = 10    # LoveIt NEW | 0.2.1 max number of results length
        snippetLength = 30      # LoveIt NEW | 0.2.3 snippet length of the result
        highlightTag = "em"     # LoveIt NEW | 0.2.1 HTML tag name of the highlight part in results
        absoluteURL = false     # LoveIt NEW | 0.2.4 whether to use the absolute URL based on the baseURL in search index

[Permalinks]
  posts = ":filename"     # posts = ":year/:month/:filename"

[sitemap]
    changefreq = "weekly"
    filename = "sitemap.xml"
    priority = 0.5

[outputs]
    home = ["HTML", "RSS", "JSON"]
    page = ["HTML", "MarkDown"]